# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fashion_Photo', models.ImageField(upload_to='Blog_Photo')),
                ('Article', models.TextField()),
                ('Author', models.TextField()),
                ('Date_Created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Photo', models.ImageField(upload_to='Blog_Photo')),
                ('Genre', models.TextField()),
                ('Article', models.TextField()),
                ('Author', models.TextField()),
                ('Date_Created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lifestyle_Photo', models.ImageField(upload_to='Blog_Photo')),
                ('Article', models.TextField()),
                ('Author', models.TextField()),
                ('Date_Created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Man_Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Man_Talk_Photo', models.ImageField(upload_to='Blog_Photo')),
                ('Article', models.TextField()),
                ('Author', models.TextField()),
                ('Date_Created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sports_Photo', models.ImageField(upload_to='Blog_Photo')),
                ('Article', models.TextField()),
                ('Author', models.TextField()),
                ('Date_Created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology_Photo', models.ImageField(upload_to='Blog_Photo')),
                ('Article', models.TextField()),
                ('Author', models.TextField()),
                ('Date_Created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trending_Photo', models.ImageField(upload_to='Blog_Photo')),
                ('Article', models.TextField()),
                ('Author', models.TextField()),
                ('Date_Created', models.DateField()),
            ],
        ),
    ]
