# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RogueKe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='Genre',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='fashion',
            name='Title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='Title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='man_talk',
            name='Title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sports',
            name='Title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='Title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trending',
            name='Title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
